# Generated by Django 4.1 on 2022-09-17 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gennum',
            old_name='net',
            new_name='net1',
        ),
    ]
