# Generated by Django 4.1 on 2022-09-04 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='Texto',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Titulo',
        ),
    ]
