# Generated by Django 4.1 on 2022-09-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_text_post_texto_rename_title_post_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Texto',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Titulo',
            new_name='title',
        ),
    ]
