# Generated by Django 4.1 on 2022-09-17 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gennum',
            name='flop',
        ),
    ]
